array_width = 0
attr_fn_like_width = 0
binop_separator = "Front"
blank_lines_lower_bound = 0
blank_lines_upper_bound = 1
chain_width = 0
combine_control_expr = false
comment_width = 120
condense_wildcard_suffixes = true
empty_item_single_line  = false
enum_discrim_align_threshold = 0
fn_call_width = 0
fn_params_layout = "Vertical"
fn_single_line = false
force_explicit_abi = true
force_multiline_blocks = true
format_code_in_doc_comments = true
format_generated_files = false
format_macro_bodies = true
format_macro_matchers = true
group_imports = "StdExternalCrate"
hard_tabs = false
hex_literal_case = "Upper"
imports_granularity = "Item"
imports_indent = "Block"
imports_layout = "Vertical"
indent_style = "Block"
inline_attribute_width = 0
match_arm_blocks = true
match_arm_leading_pipes = "Preserve"
match_block_trailing_comma = true
max_width = 100
merge_derives = true
newline_style = "Unix"
normalize_comments = true
normalize_doc_attributes = true
overflow_delimited_expr = false
remove_nested_parens = true
reorder_impl_items = true
reorder_imports = true
reorder_modules = true
short_array_element_width_threshold = 0
show_parse_errors = true
single_line_if_else_max_width = 0
single_line_let_else_max_width = 0
skip_children = false
space_after_colon = true
space_before_colon = false
spaces_around_ranges = false
struct_field_align_threshold = 0
struct_lit_single_line = false
struct_lit_width = 0
struct_variant_width = 0
tab_spaces = 4
trailing_comma = "Vertical"
trailing_semicolon = true
type_punctuation_density = "Wide"
unstable_features = true
use_field_init_shorthand = true
use_try_shorthand = true
where_single_line = false
wrap_comments = true
