[package]
name = "lgn-auth"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "0.13"
generic-array = { version = "0.14.7", default-features = false }
jwt = "0.16.0"
anyhow = "1.0.86"
elliptic-curve = { version = "0.13.5", default-features = false }
serde = { version = "1.0.202", features = ["derive"] }
ethers = { git = "https://github.com/Lagrange-Labs/ethers-rs", default-features = false, features = ["rustls"], branch = "get-proof-0x" }
ethers-core = { git = "https://github.com/Lagrange-Labs/ethers-rs", default-features = false, branch = "get-proof-0x" }
serde_json = "1.0.117"
hex = "0.4.3"
rand = "0.8.5"
