name: Open a Release PR

on:
  workflow_dispatch:
    inputs:
      bump:
        description: Release Level
        required: true
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  call-reusable-workflow:
    uses: lagrange-labs/shared-github-actions/.github/workflows/rust-prepare-release.yaml@main
    permissions:
      actions: read
      id-token: write
      pull-requests: write
      contents: write
    with:
      bump: ${{ inputs.bump }}
    secrets:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
